import { type NextPage } from "next";
import Head from "next/head";
import { getVotingOptions } from "../utils/getRandomPokemon";

const Home: NextPage = () => {
  const [first, second] = getVotingOptions();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen w-screen flex-col items-center justify-center">
        <div className="text-center text-2xl">Which Pokemon is Roundest?</div>
        <div className="mt-8 flex max-w-2xl items-center justify-between rounded border p-8">
          <div className="h-16 w-16 bg-red-500">{first}</div>
          <div className="p-8">VS</div>
          <div className="h-16 w-16 bg-blue-300">{second}</div>
        </div>
      </div>
    </>
  );
};

export default Home;
